name: Update Docker Hub images

on:
  push:
    tags: "*"

jobs:
  build:
    name: Update Docker Hub images (PM ${{ matrix.pm-version }})
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        pm-version:
          - "4"

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: Get tag name
        id: tag-name
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed 's{^refs/tags/{{')
          echo TAG_NAME=$VERSION >> $GITHUB_OUTPUT

      - name: Build image for tag
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          context: ./
          tags: |
            pmmp/poggit-phpstan:${{ steps.tag-name.outputs.TAG_NAME }}-pm${{ matrix.pm-version }}
          build-args: |
            PMMP_TAG=${{ matrix.pm-version }}

      - name: Build image for latest tag
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          context: ./
          tags: |
            pmmp/poggit-phpstan:latest-pm${{ matrix.pm-version }}
          build-args: |
            PMMP_TAG=${{ matrix.pm-version }}
